Update Rust version to 1.65.0
informalsystems/hermes pull request #2817
Opened 2022-11-04 15:44 UTC by soareschen

## Description

Update the minimum version bound of Rust to 1.65. This will allow us to make use of [new language features](https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html) in Rust, most notably Generic Associated Types.

An example use case for this is #2816.

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2022-11-04 15:50 UTC, mzabaluev requested changes
Please also update the MSRV in `README.md`.
The full checklist is in [an issue template](https://github.com/informalsystems/hermes/blob/master/.github/ISSUE_TEMPLATE/rust-update.md), which itself needs to be updated because some items no longer apply.

2022-11-04 20:05 UTC, soareschen commented
> Please also update the MSRV in `README.md`. The full checklist is in [an issue template](https://github.com/informalsystems/hermes/blob/master/.github/ISSUE_TEMPLATE/rust-update.md), which itself needs to be updated because some items no longer apply.

Done.

2022-11-05 11:13 UTC, romac approved these changes

2022-11-05 13:17 UTC, mzabaluev approved these changes

2022-11-07 09:36 UTC, merged