Clean up documentation for simple example integration test
informalsystems/hermes pull request #2933
Opened 2022-12-09 20:34 UTC by seanchen1991

Part of #2737.

## Description

As a first stab at improving the documentation of the integration test framework, this PR moves the documentation of the simple example integration test that previously lived at `tools/integration-test/src/tests/example.rs` into `tools/test-framework/src/docs/`. Going forward, we'll centralize the documentation of the framework in this directory. 

Follow up PRs will add more docs walking through more complex integration tests in order to illustrate different use cases and recipes for using the test framework.
______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2022-12-12 11:35 UTC, adizere commented
> Follow up PRs will add more docs walking through more complex integration tests in order to illustrate different use cases and recipes for using the test framework.

Should we open a follow-up issue to capture these needs? Then the present PR can close #2737.

2022-12-12 16:07 UTC, seanchen1991 commented
> Should we open a follow-up issue to capture these needs

Added #2937 to capture the additional work.

2022-12-12 20:37 UTC, soareschen requested changes
There are a couple of cargo doc warnings to fix.

2022-12-12 20:37 UTC, soareschen commented on tools/test-framework/src/docs/walkthroughs/simple.rs
> +//! [`BinaryChannelTest`](ibc_test_framework::framework::binary::channel::BinaryChannelTest),
There are warnings in broken cargo doc links. I think we have to use `crate::` here, since we are referring to the same crate.

2022-12-12 20:37 UTC, soareschen commented on tools/test-framework/src/docs/walkthroughs/simple.rs
> +//! 1. `config`: for accessing any relayer configuration values during the course of the test
This is the test config, not the relayer config.

2023-01-03 11:49 UTC, soareschen approved these changes

2023-01-03 14:34 UTC, merged