Fix packet forwarding tests
informalsystems/hermes pull request #3032
Opened 2023-01-24 12:27 UTC by ljoss17

Closes: #3025

## Description

This PR updates the tests for Packet Forwarding.
As of version `3.0.0`, https://github.com/strangelove-ventures/packet-forward-middleware/releases/tag/v3.0.0, of the packet-forward-middleware, the memo field is used instead of a specific receiver address, see https://github.com/strangelove-ventures/packet-forward-middleware#examples.

## Chains using new packet-forward-middleware

* `simd` starting from version `5.1.0`, 
* `gaiad` starting from version `8.0.0-rc1`, https://github.com/cosmos/gaia/blob/main/CHANGELOG.md#v800-rc1---2023-01-06

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [x] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [x] Linked to GitHub issue.
- [ ] ~Updated code comments and documentation (e.g., `docs/`).~
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2023-01-24 13:22 UTC, soareschen commented on tools/test-framework/src/chain/cli/transfer.rs
> +    simple_exec(
Once this is working, we should update `ibc-proto-rs` to include the memo field, and have another PR to update this method to submit the transaction within Rust.

2023-01-24 13:30 UTC, romac requested changes

2023-01-24 13:30 UTC, romac commented on tools/integration-test/src/tests/mod.rs
> +//#[cfg(any(doc, feature = "forward-packet"))]
We probably need to uncomment this, otherwise we will be running these tests for all chains defined in the workflow

2023-01-25 13:04 UTC, romac approved these changes

2023-01-25 14:35 UTC, merged

2023-01-25 14:35 UTC, romac commented
💯