Detect light client attacks and report them to both the chain and the RPC node
informalsystems/hermes pull request #3224
Opened 2023-04-04 13:28 UTC by romac

Closes: #3223

## Description

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2023-04-14 10:13 UTC, ancazamfir requested changes
Great work @romac!!! Did a fist pass in parallel with the `tendermint-rs` changes.

2023-04-14 15:36 UTC, romac commented on crates/relayer/src/light_client/tendermint.rs
> +        let now = latest_chain_block.time(); // FIXME: Is that right?
9b9ffce8cf5372c3d66fb6f5271d65c8c55c92ea

2023-04-18 08:04 UTC, romac commented on crates/relayer/src/light_client/tendermint.rs
> +                    supporting_headers: vec![], // FIXME: What do we put here?
Won't the trace typically only contain the target and trusted headers? Do we really need to supply them as supporting headers in that case?

2023-04-26 15:10 UTC, romac commented on crates/relayer/src/foreign_client.rs
> +                // FIXME: This is fishy
FIXME: This is fishy

2023-04-26 15:10 UTC, romac commented on crates/relayer/src/foreign_client.rs
> +                // FIXME: This is fishy
FIXME: This is fishy

2023-04-27 05:19 UTC, ancazamfir commented on crates/relayer/src/foreign_client.rs
> +        // FIXME(romac): Why do we need this, and shouldn't we wait somewhere else up the call stack?
I am not sure. Let's open a separate issue and investigate there.

2023-04-27 14:50 UTC, romac commented on crates/relayer/src/light_client/tendermint.rs
> +        let trusted_block = self.fetch(update_header.trusted_height)?; // TODO: Check validator sets match
Right, I hadn't thought of that. Yeah let's go with an error for now.

2023-04-28 08:22 UTC, romac commented on crates/relayer/src/light_client/tendermint.rs
> +        let trusted_block = self.fetch(update_header.trusted_height)?; // TODO: Check validator sets match
[`5f253fe` (#3224)](https://github.com/informalsystems/hermes/pull/3224/commits/5f253fef11815fa30838d01b5dbc67e2689012cd)

2023-05-05 08:37 UTC, ancazamfir approved these changes
Amazing job @romac!

2023-05-19 10:07 UTC, ancazamfir commented on crates/relayer/src/foreign_client.rs
> +        // FIXME(romac): Why do we need this, and shouldn't we wait somewhere else up the call stack?
see #3351

2023-05-19 10:07 UTC, ancazamfir commented on crates/relayer/src/foreign_client.rs
> +                // FIXME: This is fishy
see #3351

2023-05-19 10:08 UTC, merged