Implement packet clearing in relayer next
informalsystems/hermes pull request #3488
Opened 2023-07-18 08:19 UTC by ljoss17

Closes: #XXX

## Description

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2023-08-02 10:07 UTC, ljoss17 commented on crates/relayer-cosmos/src/methods/unreceived_packet.rs
> +    for sequence in sequences.iter() {
From what I understand `query_send_packet_events` from `crates/relayer/src/link/packet_events.rs` does the following:

1. Build the `QueryPacketEventDataRequest` and call `query_packet_events`
2. If the height is `Qualified::Equal` query the packets from block (not currently done in the this implementation for relayer-next)
3. If the height is `Qualified::SmallerEqual` query the packets from TXs
4. `query_packet_from_txs` calls `tx_search(packet_query(..))` for each sequence number, similar to what is being done in this implementation
	1. With the addition of mapping the ABCI events to `IbcEventWithHeight` by calling `packet_from_tx_search_response`.

I don't see how this is more efficient, and the issue is that the cosmos implementation uses ABCI Events as its `Event` type so `try_extract_send_packet_event` expects an ABCI Event and not a `IbcEventWithHeight`.

And `query_packet_events_with` from `crates/relayer/src/link/packet_events.rs` is called with `query_send_packet_events` and `query_write_ack_events` as `query_fn`, so it also ends up calling `query_packet_events`.

2023-08-02 10:25 UTC, ljoss17 commented on crates/relayer-components/src/chain/traits/queries/unreceived_packets.rs
> +    ) -> Result<(Vec<Self::Sequence>, Self::Height), Self::Error>;
Fixed in https://github.com/informalsystems/hermes/pull/3488/commits/92c386ff67c5d0b0ba43b11c80d2055a4bd1cd74

2023-08-02 10:27 UTC, ljoss17 commented on crates/relayer-components/src/chain/traits/queries/unreceived_packets.rs
> +pub trait CanQueryUnreceivedPackets<Counterparty>:
Fixed in https://github.com/informalsystems/hermes/pull/3488/commits/11da2e4f25c3da2027d05395969c7ccef913b422

2023-08-02 10:28 UTC, ljoss17 commented on crates/relayer-components/src/chain/traits/queries/unreceived_packets.rs
> +        sequences: &[Counterparty::Sequence],
Fixed in https://github.com/informalsystems/hermes/pull/3488/commits/92c386ff67c5d0b0ba43b11c80d2055a4bd1cd74

2023-08-02 10:28 UTC, ljoss17 commented on tools/integration-test/src/tests/next/packet_clear.rs
> +                    relay_context.relay_a_to_b().src_chain(),
Fixed in https://github.com/informalsystems/hermes/pull/3488/commits/e0b57276ffac462d71f87fe62aa5d397711560d6

2023-08-02 10:30 UTC, ljoss17 commented on crates/relayer-components/src/chain/traits/queries/packet_commitments.rs
> +    async fn query_packet_commitments(
Fixed in https://github.com/informalsystems/hermes/pull/3488/commits/92c386ff67c5d0b0ba43b11c80d2055a4bd1cd74 and https://github.com/informalsystems/hermes/pull/3488/commits/132ae5d017275e9d40f921b77453a23ee0a622bd

2023-08-02 10:30 UTC, ljoss17 commented on crates/relayer-components/src/chain/traits/queries/unreceived_packets.rs
> +        height: &Counterparty::Height,
Fixed in https://github.com/informalsystems/hermes/pull/3488/commits/495bffb8b2657adedecc163142a67552d091c7e7

2023-08-03 08:56 UTC, soareschen commented on crates/relayer-cosmos/src/methods/unreceived_packet.rs
> +    for sequence in sequences.iter() {
Hmm you are right. Looks like the algorithm is ultimately based on `query_packets_from_txs` in `crates/relayer/src/chain/cosmos/query/tx.rs`. Maybe we should note that down and add a todo for investigating more efficient approach.

One more nit for this: it should be possible to use the [`Stream` construct with `.map()`](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.map) to query for all events in parallel and then collect them into a vec.

2023-08-03 08:59 UTC, soareschen commented on crates/relayer-cosmos/src/methods/unreceived_packet.rs
> +    for sequence in sequences.iter() {
Probably a more structured way to define this is to first define a `CanQuerySendPacketsFromSequence` trait (without -s), and then implement `CanQuerySendPacketsFromSequences` by using `Stream::map` and calling the singular method for each sequence.

2023-08-03 09:20 UTC, soareschen requested changes

2023-08-03 09:20 UTC, soareschen commented on crates/relayer-components/src/chain/traits/queries/unreceived_packets.rs
> +    async fn query_unreceived_packets(
The name of the method should also change to `query_send_packets_from_sequences`. Also, let's move this trait to a separate file like `send_packets.rs`.

2023-08-04 14:14 UTC, soareschen approved these changes

2023-08-04 14:14 UTC, merged