test: add workflow trigger by gaia
informalsystems/hermes pull request #3561
Opened 2023-08-24 13:54 UTC by yaruwangway

Closes: #XXX

## Description

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2023-08-24 13:59 UTC, yaruwangway commented on .github/workflows/test_for_gaia.yml
> +          CHAIN_COMMAND_PATHS=${{ github.workspace }}/gaia/build/gaiad ACCOUNT_PREFIXES=cosmos cargo test -p ibc-integration-test -- tests::transfer::test_ibc_transfer
more test will be add after the setup is tested.

2023-08-25 12:09 UTC, romac requested changes

2023-08-25 12:09 UTC, romac commented on .github/workflows/test_for_gaia.yml
> +name: Test Triggered by Gaia
```suggestion
name: Test new Gaia release
```

2023-08-25 12:09 UTC, romac commented on .github/workflows/test_for_gaia.yml
> +          CHAIN_COMMAND_PATHS=${{ github.workspace }}/gaia/build/gaiad ACCOUNT_PREFIXES=cosmos cargo test -p ibc-integration-test -- tests::transfer::test_ibc_transfer
```suggestion
          cargo test -p ibc-integration-test -- tests::transfer::test_ibc_transfer
```

2023-08-25 12:09 UTC, romac commented on .github/workflows/test_for_gaia.yml
> +        ACCOUNT_PREFIXES: ${{ matrix.chain.account_prefix }}
```suggestion
        CHAIN_COMMAND_PATHS: ${{ github.workspace }}/gaia/build/gaiad
        ACCOUNT_PREFIXES: cosmos
```

2023-08-25 12:09 UTC, romac commented on .github/workflows/test_for_gaia.yml
> +    - name: Checkout hermes version
```suggestion
    - name: Checkout Hermes ${{ github.event.client_payload.hermes_version }}
```

2023-08-25 12:09 UTC, romac commented on .github/workflows/test_for_gaia.yml
> +    - name: Fetch Gaia Repo
```suggestion
    - name: Build Gaia ${{ github.event.client_payload.gaiad_version }}
```

2023-08-25 14:28 UTC, yaruwangway commented
Hi, I put this in blocked for now, we might want to do it differently. Thank you for reviewing!

2023-09-06 14:58 UTC, romac commented
@yaruwangway I am closing this, feel free to re-open if you choose to stick with this approach.

2023-09-06 14:58 UTC, closed without merging

2023-11-08 22:07 UTC, vehicles4real commented
Thanks

2023-11-08 22:07 UTC, vehicles4real commented
Thanks