Add `Penumbra support` to Features Matrix.
informalsystems/hermes pull request #3685
Opened 2023-11-04 04:03 UTC by jonathanpberger

Penumbra (non-`cosmos-SDK`) support was added to the go-relayer in https://github.com/cosmos/relayer/pull/1144 on March 31, 2023.

2023-11-07 10:31 UTC, romac requested changes

2023-11-07 10:31 UTC, romac commented on guide/src/advanced/features.md
> +| Chain_Non_Cosmos       | ❌    | ✅     | supports non cosmos-SDK chains
```suggestion
| Chain_Non_Cosmos       | 🚧    | ✅     | supports non Cosmos-SDK chains (better support for non-Cosmos-SDK chains is a work-in-progress, see the [Hermes SDK](https://github.com/informalsystems/hermes-sdk))
```

2023-11-07 21:31 UTC, jonathanpberger commented on guide/src/advanced/features.md
> +| Penumbra support       | ❌    | ✅     | supports Penumbra non-cosmos-SDK chain
I can't vouch for the content ("...Hermes support is a [work-in-progress]...") of these requested changes, and would n't be comfortable including them. Maybe submit them as a subsequent PR?

2023-11-09 09:14 UTC, romac commented on guide/src/advanced/features.md
> +| Penumbra support       | ❌    | ✅     | supports Penumbra non-cosmos-SDK chain
Sure that's fine, we can merge as-is.

2023-11-09 09:14 UTC, merged