Add configuration to skip packet sequences when clearing
informalsystems/hermes pull request #3862
Opened 2024-02-29 12:19 UTC by ljoss17

Closes: #3754

## Description

This PR adds a per-chain configuration `excluded_sequences` that can be used to specify which packet sequences should not be cleared when clearing is triggered.

This filter is only applied to pending packets cleared, standard relaying is not affected by the filter.

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [x] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [x] Linked to GitHub issue.
- [x] Updated code comments and documentation (e.g., `docs/`).
- [x] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2024-02-29 12:59 UTC, romac requested changes

2024-02-29 13:05 UTC, romac commented on config.toml
> +# excluded_sequences = []
I also wonder if we should allow sequence ranges in there, but not sure how to best express them in TOML. Maybe we leave this for a follow-up.

2024-02-29 13:11 UTC, ljoss17 commented on config.toml
> +# excluded_sequences = []
Oh good point, I will update this and add a second channel to the tests to insure that everything works as expected

2024-03-06 08:30 UTC, romac approved these changes

2024-03-06 14:08 UTC, merged